name: Backend CI/CD

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run JUnit tests
        run: ./backend/mvnw -B clean test -f ./backend/pom.xml


  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build backend artifact
        run: ./backend/mvnw -B package -DskipTests -f ./backend/pom.xml


      # ----------------------------
      # CONFIGURE AWS
      # ----------------------------

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      # ----------------------------
      # BUILD DOCKER IMAGES
      # ----------------------------

      - name: Build backend Docker image
        run: docker build -t backend-image ./backend

      - name: Build frontend Docker image
        run: docker build -t frontend-image ./react


      # ----------------------------
      # PUSH BACKEND IMAGE
      # ----------------------------

      - name: Tag and push backend image
        run: |
          docker tag backend-image \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ vars.ECR_Backend }}:${{ github.sha }}

          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ vars.ECR_Backend }}:${{ github.sha }}


      # ----------------------------
      # PUSH FRONTEND IMAGE
      # ----------------------------

      - name: Tag and push frontend image
        run: |
          docker tag frontend-image \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ vars.ECR_Frontend }}:${{ github.sha }}

          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ vars.ECR_Frontend }}:${{ github.sha }}


      # =====================================================
      # BACKEND DEPLOY
      # =====================================================

      - name: Download Backend Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition digital-menu-backend \
            --query taskDefinition \
            > backend-task-full.json
      
          cat backend-task-full.json \
          | jq 'del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy,
              .enableFaultInjection
            )' \
          > backend-task.json

      - name: Render Backend Task Definition
        id: backend-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: backend-task.json
          container-name: digital-menu-backend-container
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ vars.ECR_Backend }}:${{ github.sha }}

      - name: Deploy Backend Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.backend-task.outputs.task-definition }}
          service: digital-menu-backend-service-zaionya6
          cluster: digital-menu-ecs-cluster
          wait-for-service-stability: true


      # =====================================================
      # FRONTEND DEPLOY
      # =====================================================

      - name: Download Frontend Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition digital-menu-frontend \
            --query taskDefinition \
            > frontend-task-full.json
      
          cat frontend-task-full.json \
          | jq 'del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy,
              .enableFaultInjection
            )' \
          > frontend-task.json

      - name: Render Frontend Task Definition
        id: frontend-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: frontend-task.json
          container-name: digital-menu-frontend-container
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ vars.ECR_Frontend }}:${{ github.sha }}

      - name: Deploy Frontend Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.frontend-task.outputs.task-definition }}
          service: digital-menu-frontend-service-h680ldkz
          cluster: digital-menu-ecs-cluster
          wait-for-service-stability: true
